import React, { createContext, useContext, useMemo, useState } from 'react';
import { Bot, ChevronRight, Send, X } from 'lucide-react';
import { useLocation } from 'react-router-dom';

const Context=createContext(null);
const responses={
 'Why is the schedule at risk?':{answer:'Physical progress is below the planned trajectory, the revised completion date moved, and two milestone checkpoints show slippage.',evidence:'Monthly Progress Report — June 2026'},
 'Which milestone is delayed?':{answer:'Mid Execution is recorded as delayed, while Major Completion remains at risk against the revised timeline.',evidence:'Milestone evidence snapshot — June 2026'},
 'What is the latest cost status?':{answer:'Revised cost is ₹3,980 Cr and cumulative expenditure is ₹2,104 Cr. Final-cost forecasting is not available.',evidence:'Project cost summary — June 2026'},
 'Show key concerns.':{answer:'Current concerns are slower physical progress, timeline movement, milestone slippage and expenditure-to-progress alignment.',evidence:'PRAHARI project evidence view'},
};
export function AskPrahariProvider({children}){const [open,setOpen]=useState(false);return <Context.Provider value={{open,setOpen}}>{children}</Context.Provider>}
export function AskPrahariLauncher(){const {setOpen}=useContext(Context);return <button className="assistant-launcher" type="button" onClick={()=>setOpen(true)}><span><Bot/></span><b>Ask PRAHARI<small>Get quick insights</small></b></button>}
export function AskPrahariDrawer(){const {open,setOpen}=useContext(Context);const location=useLocation();const projectContext=location.pathname.includes('/projects/');const suggestions=projectContext?Object.keys(responses):['Summarize projects needing attention','What changed this month?','Show reviews assigned to me'];const [answer,setAnswer]=useState(null);const context=useMemo(()=>projectContext?'Bhatadi Expansion OC':'Portfolio overview',[projectContext]);return <aside className={`assistant-drawer ${open?'open':''}`} aria-hidden={!open} aria-label="Ask PRAHARI assistant"><header className="assistant-head"><span><Bot/></span><div><h2>Ask PRAHARI</h2><p>{context}</p></div><button onClick={()=>setOpen(false)} aria-label="Close Ask PRAHARI"><X/></button></header><div className="assistant-body"><p className="assistant-greeting">How can I help with this {projectContext?'project':'portfolio'}?</p><div className="assistant-prompts">{suggestions.map(q=><button key={q} onClick={()=>setAnswer(responses[q]||{answer:'This prototype response will be connected to governed project evidence during backend integration.',evidence:'Frontend demonstration context'})}>{q}<ChevronRight/></button>)}</div>{answer&&<article className="assistant-message"><h3>Answer</h3><p>{answer.answer}</p><h4>Key evidence</h4><p>{answer.evidence}</p><small>Verify material decisions against the cited project record.</small></article>}</div><footer className="assistant-form"><label><span className="sr-only">Ask a question</span><input placeholder="Ask about this project or portfolio…"/><button aria-label="Send question"><Send/></button></label><small>PRAHARI can make mistakes. Verify important information.</small></footer></aside>}
