import React, { createContext, useContext, useEffect, useMemo, useRef, useState } from 'react';
import { BrainCircuit, ChevronRight, FileCheck2, Maximize2, Minus, Send, Sparkles, Trash2, X } from 'lucide-react';
import { useLocation } from 'react-router-dom';
import { contextPrompts } from '../../data/mock/askPrahariResponses';
import { assistantService } from '../../services/assistant/AssistantService';

const Context=createContext(null);const HISTORY_KEY='prahari-assistant-history';
const readHistory=()=>{try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]')}catch{return []}};
export function AskPrahariProvider({children}){const [open,setOpen]=useState(false);return <Context.Provider value={{open,setOpen}}>{children}</Context.Provider>}
export function AskPrahariLauncher(){const {open,setOpen}=useContext(Context);return <button className={`assistant-launcher ${open?'active':''}`} type="button" onClick={()=>setOpen(true)}><span><BrainCircuit/></span><b>Ask PRAHARI<small>Project Intelligence Assistant</small></b><i aria-hidden="true"/></button>}
export function AskPrahariDrawer(){
 const {open,setOpen}=useContext(Context);const location=useLocation();const [input,setInput]=useState('');const [messages,setMessages]=useState(readHistory);const [typing,setTyping]=useState(false);const [minimized,setMinimized]=useState(false);const bodyRef=useRef(null);
 const kind=location.pathname.includes('/alerts/')?'alert':location.pathname.includes('/reviews/')?'review':location.pathname.includes('/projects/')?'project':'portfolio';
 const context=useMemo(()=>kind==='project'?'BHATADI Expansion OC · PRH-400033':kind==='alert'?'Active alert evidence':kind==='review'?'Officer review workflow':'National portfolio overview',[kind]);const suggestions=contextPrompts[kind];
 useEffect(()=>{localStorage.setItem(HISTORY_KEY,JSON.stringify(messages))},[messages]);
 useEffect(()=>{if(!open)return;const close=e=>{if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[open,setOpen]);
 useEffect(()=>{const body=bodyRef.current;if(body&&typeof body.scrollTo==='function')body.scrollTo({top:body.scrollHeight,behavior:'smooth'})},[messages,typing]);
 const ask=async q=>{const text=q.trim();if(!text||typing)return;setMessages(m=>[...m,{role:'user',text}]);setInput('');setTyping(true);try{const response=await assistantService.ask({question:text,context:{kind,label:context},history:messages});setMessages(m=>[...m,{role:'assistant',...response}])}catch{setMessages(m=>[...m,{role:'assistant',summary:'Project intelligence is temporarily unavailable.',evidence:[],action:'Please retry or open the relevant evidence panel.',sources:[]}])}finally{setTyping(false)}};
 const clear=()=>{setMessages([]);localStorage.removeItem(HISTORY_KEY)};const submit=e=>{e.preventDefault();ask(input)};
 return <aside className={`assistant-drawer ${open?'open':''} ${minimized?'minimized':''}`} aria-hidden={!open} aria-label="Ask PRAHARI assistant"><header className="assistant-head"><span><BrainCircuit/></span><div><h2>Ask PRAHARI</h2><p>Project Intelligence Assistant</p></div><button onClick={clear} aria-label="Clear conversation" title="Clear conversation"><Trash2/></button><button onClick={()=>setMinimized(!minimized)} aria-label={minimized?'Expand Ask PRAHARI':'Minimize Ask PRAHARI'}>{minimized?<Maximize2/>:<Minus/>}</button><button onClick={()=>{setOpen(false);setMinimized(false)}} aria-label="Close Ask PRAHARI"><X/></button></header><div className="assistant-context"><FileCheck2/><span><small>Working context</small><strong>{context}</strong></span><b>Evidence bounded</b></div><div className="assistant-body" ref={bodyRef}>{messages.length===0&&<section className="assistant-welcome"><span><Sparkles/></span><h3>{kind==='project'?'How can I help with BHATADI Expansion OC?':'What intelligence would you like to review?'}</h3><p>Ask for a concise, source-aware briefing to support your next action.</p></section>}<div className="assistant-prompts">{suggestions.slice(0,messages.length?3:6).map(q=><button key={q} onClick={()=>ask(q)}>{q}<ChevronRight/></button>)}</div><div className="assistant-history">{messages.map((m,i)=>m.role==='user'?<p className="assistant-user" key={i}>{m.text}</p>:<article className="assistant-message" key={i}><span className="response-label">PRAHARI assessment</span><h3>Answer</h3><p>{m.summary}</p>{m.evidence?.length>0&&<><h4>Key evidence</h4><ul>{m.evidence.map(x=><li key={x}>{x}</li>)}</ul></>}{m.action&&<div className="assistant-action"><strong>Recommended attention</strong><p>{m.action}</p></div>}{m.sources?.length>0&&<div className="assistant-sources"><strong>Sources</strong>{m.sources.map(x=><span key={x}>{x}</span>)}</div>}</article>)}{typing&&<div className="assistant-typing" role="status"><i/><i/><i/><span>Reviewing project evidence</span></div>}</div></div><footer className="assistant-form"><form onSubmit={submit}><label><span className="sr-only">Ask a question</span><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask for project intelligence…"/><button type="submit" disabled={!input.trim()||typing} aria-label="Send question"><Send/></button></label></form><small>Decision support only · Verify material decisions against the cited record.</small></footer></aside>
}
