import React, { createContext, useContext, useEffect, useMemo, useRef, useState } from 'react';
import { Bot, ChevronRight, Maximize2, Minus, Send, X } from 'lucide-react';
import { useLocation } from 'react-router-dom';
import { contextPrompts, resolveDemoQuestion } from '../../data/mock/askPrahariResponses';

const Context=createContext(null);
export function AskPrahariProvider({children}){const [open,setOpen]=useState(false);return <Context.Provider value={{open,setOpen}}>{children}</Context.Provider>}
export function AskPrahariLauncher(){const {setOpen}=useContext(Context);return <button className="assistant-launcher" type="button" onClick={()=>setOpen(true)}><span><Bot/></span><b>Ask PRAHARI<small>Get quick insights</small></b></button>}
export function AskPrahariDrawer(){
 const {open,setOpen}=useContext(Context);const location=useLocation();const [input,setInput]=useState('');const [messages,setMessages]=useState([]);const [typing,setTyping]=useState(false);const [minimized,setMinimized]=useState(false);const bodyRef=useRef(null);
 const kind=location.pathname.includes('/alerts/')?'alert':location.pathname.includes('/reviews/')?'review':location.pathname.includes('/projects/')?'project':'portfolio';
 const context=useMemo(()=>kind==='project'?'Project intelligence':kind==='alert'?'Alert evidence':kind==='review'?'Officer review':'Portfolio overview',[kind]);const suggestions=contextPrompts[kind];
 useEffect(()=>{if(!open)return;const close=e=>{if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[open,setOpen]);
 useEffect(()=>{const body=bodyRef.current;if(body&&typeof body.scrollTo==='function')body.scrollTo({top:body.scrollHeight,behavior:'smooth'})},[messages,typing]);
 const ask=q=>{const text=q.trim();if(!text||typing)return;setMessages(m=>[...m,{role:'user',text}]);setInput('');setTyping(true);window.setTimeout(()=>{setMessages(m=>[...m,{role:'assistant',...resolveDemoQuestion(text)}]);setTyping(false)},350)};
 const submit=e=>{e.preventDefault();ask(input)};
 return <aside className={`assistant-drawer ${open?'open':''} ${minimized?'minimized':''}`} aria-hidden={!open} aria-label="Ask PRAHARI assistant"><header className="assistant-head"><span><Bot/></span><div><h2>Ask PRAHARI</h2><p>{context}</p></div><button onClick={()=>setMinimized(!minimized)} aria-label={minimized?'Expand Ask PRAHARI':'Minimize Ask PRAHARI'}>{minimized?<Maximize2/>:<Minus/>}</button><button onClick={()=>{setOpen(false);setMinimized(false)}} aria-label="Close Ask PRAHARI"><X/></button></header><div className="assistant-body" ref={bodyRef}><p className="assistant-greeting">This deterministic demo answers curated, evidence-bounded questions for the current {kind}.</p><div className="assistant-prompts">{suggestions.map(q=><button key={q} onClick={()=>ask(q)}>{q}<ChevronRight/></button>)}</div><div className="assistant-history">{messages.map((m,i)=>m.role==='user'?<p className="assistant-user" key={i}>{m.text}</p>:<article className="assistant-message" key={i}><h3>Answer</h3><p>{m.answer}</p><h4>Key evidence</h4><p>{m.evidence}</p><small>Verify material decisions against the cited project record.</small></article>)}{typing&&<div className="assistant-typing" role="status">Reviewing demo evidence<span>…</span></div>}</div></div><footer className="assistant-form"><form onSubmit={submit}><label><span className="sr-only">Ask a question</span><input value={input} onChange={e=>setInput(e.target.value)} placeholder={`Ask about this ${kind}…`}/><button type="submit" disabled={!input.trim()||typing} aria-label="Send question"><Send/></button></label></form><small>Deterministic prototype responses only. Verify important information.</small></footer></aside>
}
