import React from 'react';

const palette={healthy:'#16a36a',monitor:'#1685d0',attention:'#efa61b',high:'#e83b58',limited:'#9aaebe',purple:'#7655d8',cyan:'#28b5d9'};

export function PortfolioTrend(){const actual=[44,47,49,52,55,58,62];const planned=[46,50,55,60,66,72,78];const x=i=>48+i*72;const y=v=>176-(v-35)*3;const points=a=>a.map((v,i)=>`${x(i)},${y(v)}`).join(' ');return <div className="analytics-chart"><div className="chart-legend-row"><span><i style={{background:palette.monitor}}/>Actual progress</span><span><i style={{background:palette.healthy}}/>Planned progress</span></div><svg viewBox="0 0 520 215" role="img" aria-label="Portfolio physical progress, actual versus planned, December 2025 to June 2026">{[40,50,60,70,80].map(v=><g key={v}><line x1="42" x2="492" y1={y(v)} y2={y(v)} className="grid-line"/><text x="5" y={y(v)+4}>{v}%</text></g>)}<polyline points={points(planned)} className="trend planned"/><polyline points={points(actual)} className="trend actual"/>{actual.map((v,i)=><circle key={i} cx={x(i)} cy={y(v)} r="4" className="actual-point"><title>{['Dec','Jan','Feb','Mar','Apr','May','Jun'][i]} 2026 · Actual {v}% · Planned {planned[i]}%</title></circle>)}{['Dec','Jan','Feb','Mar','Apr','May','Jun'].map((m,i)=><text key={m} x={x(i)} y="203" textAnchor="middle">{m}</text>)}<g className="last-label"><rect x="452" y={y(62)-26} width="50" height="20" rx="5"/><text x="477" y={y(62)-12} textAnchor="middle">62%</text></g></svg></div>}

const sectors=[['Coal',118,76,42,28],['Transport',132,64,34,18],['Energy',94,55,31,14],['Water',72,38,22,8],['Urban',66,42,29,11],['Others',84,48,27,15]];
export function SectorHealth(){return <div className="sector-health"><div className="chart-legend-row">{[['Healthy','healthy'],['Monitor','monitor'],['Needs attention','attention'],['High concern','high']].map(([l,k])=><span key={l}><i style={{background:palette[k]}}/>{l}</span>)}</div>{sectors.map(([name,...values])=>{const total=values.reduce((a,b)=>a+b,0);return <div className="sector-row" key={name}><b>{name}</b><div className="stacked-bar">{values.map((v,i)=><span key={i} style={{width:`${v/total*100}%`,background:[palette.healthy,palette.monitor,palette.attention,palette.high][i]}}><title>{name} · {['Healthy','Monitor','Needs attention','High concern'][i]}: {v} projects</title></span>)}</div><small>{total}</small></div>})}</div>}

export function QualityCoverage(){const items=[['Good',2351,82,palette.healthy],['Needs verification',344,12,palette.attention],['Limited information',172,6,palette.limited]];return <div className="quality-chart"><div className="quality-donut"><div><strong>82%</strong><span>good coverage</span><small>2,351 projects</small></div></div><div className="quality-legend">{items.map(([l,c,p,color])=><div key={l}><i style={{background:color}}/><span>{l}<small>{p}% of portfolio</small></span><b>{c.toLocaleString('en-IN')}</b></div>)}</div></div>}

export function DistributionChart({type='schedule'}){const items=type==='schedule'?[['On track',1747,61,palette.healthy],['Monitor',906,32,palette.monitor],['High concern',214,7,palette.high]]:[['No revision',1892,66,palette.healthy],['Revised',731,25,palette.attention],['Elevated pressure',244,9,palette.high]];return <div className="distribution-chart"><div className="distribution-track">{items.map(([l,,p,c])=><span key={l} style={{width:`${p}%`,background:c}}><title>{l}: {p}%</title></span>)}</div>{items.map(([l,c,p,color])=><div className="distribution-row" key={l}><i style={{background:color}}/><span>{l}</span><b>{c.toLocaleString('en-IN')}</b><small>{p}%</small></div>)}</div>}

const comparisons=[['Physical progress',62,71,'%'],['Expenditure ratio',53,48,'%'],['Schedule movement',9,5,'months'],['Cost revision',22,14,'%']];
export function PeerComparison(){return <div className="peer-chart"><div className="chart-legend-row"><span><i style={{background:palette.monitor}}/>BHATADI</span><span><i style={{background:palette.cyan}}/>Similar coal projects median</span></div>{comparisons.map(([label,project,peer,unit])=>{const max=Math.max(project,peer)*1.2;return <div className="peer-row" key={label}><strong>{label}</strong><div><span className="project" style={{width:`${project/max*100}%`}}><i>{project}{unit}</i></span><span className="peer" style={{width:`${peer/max*100}%`}}><i>{peer}{unit}</i></span></div></div>})}<p>Observational comparison across 18 open-cast coal projects. Values describe the reporting record and do not imply causality.</p></div>}
