import React from 'react';
import { Link } from 'react-router-dom';
import { Bell, Bookmark, CheckCircle2, Download, FileText, FolderKanban, TrendingDown, TrendingUp, UserRound } from 'lucide-react';
import IndiaMap from '../../components/charts/IndiaMap';
import { Bars, Donut, LineChart } from '../../components/charts/MiniCharts';
import { FilterBar, KpiStrip, MetricPage, PageHeroHeader, Section, StandardTable, StatusPill } from '../../components/common/PageKit';
import { attentionKpis, projectKpis, projects } from '../../data/mock/projects';
import { monitoring, notifications, reports } from '../../data/mock/supporting';

const projectColumns=[{key:'project',label:'Project / Code'},{key:'ministry',label:'Ministry / Agency / Sector'},{key:'state',label:'State / Region'},{key:'phase',label:'Stage / Phase'},{key:'schedule',label:'Schedule'},{key:'cost',label:'Cost'},{key:'health',label:'Execution Health'},{key:'quality',label:'Data Quality'},{key:'actionState',label:'Officer Action'},{key:'action',label:'Action'}];
const projectCell=(p,key)=>key==='project'?<><span className="project-name">{p.name}</span><span className="project-code">{p.id}</span></>:key==='ministry'?<>{p.ministry}<span className="project-code">{p.agency} · {p.sector}</span></>:['schedule','cost','health','quality','actionState'].includes(key)?<StatusPill>{key==='actionState'?p.action:p[key]}</StatusPill>:key==='action'?<Link className="btn secondary" to={`/officer/projects/${p.id}`}>Open dossier</Link>:p[key];

export function ProjectsPage(){return <MetricPage title="Projects" subtitle="Browse, filter and open project intelligence dossiers across the monitored portfolio." kpis={projectKpis} filters={['Ministry','Sector','State','Execution Health','Officer Action','Data Quality']} rail={<aside className="stack"><Section title="Saved Views"><div className="side-list">{[['High concern projects','214'],['My review queue','98'],['North East region','176'],['Strategic projects','52']].map(x=><button key={x[0]}><Bookmark/>{x[0]}<b>{x[1]}</b></button>)}</div></Section><Section title="Status legend"><div className="legend-list"><StatusPill>On track</StatusPill><StatusPill>Monitor</StatusPill><StatusPill>High concern</StatusPill><StatusPill>Needs verification</StatusPill></div></Section></aside>}><Section title="Project list" action={<span className="section-meta">Showing {projects.length} of 2,867 projects</span>}><StandardTable columns={projectColumns} rows={projects} renderCell={projectCell}/></Section></MetricPage>}

export function AttentionPage(){const cols=[{key:'project',label:'Project'},{key:'attention',label:'Attention'},{key:'concern',label:'Primary Concern'},{key:'quality',label:'Data Quality'},{key:'forecast',label:'Forecast'},{key:'assigned',label:'Assigned'},{key:'updated',label:'Updated'},{key:'action',label:'Action'}];const rows=projects.slice(0,6).map((p,i)=>({...p,project:p.name,attention:p.action,concern:['Progress slowing','Cost pressure','Land readiness','Reporting gap'][i%4],forecast:p.schedule,assigned:['R. Kumar','S. Mehta','A. Singh'][i%3],updated:'Jun 2026'}));return <MetricPage title="Attention Queue" subtitle="Projects requiring review, verification or closer monitoring." kpis={attentionKpis} filters={['Attention Type','Sector','Ministry','State','Priority','Assigned Officer','Reporting Period']}><Section title="Prioritized officer work queue" action={<span className="section-meta">Ordered by governed priority</span>}><StandardTable columns={cols} rows={rows} renderCell={(r,k)=>k==='project'?<><span className="project-name">{r.name}</span><span className="project-code">{r.id}</span></>:['attention','quality','forecast'].includes(k)?<StatusPill>{r[k]}</StatusPill>:k==='action'?<Link className="btn secondary" to={`/officer/projects/${r.id}`}>Review project</Link>:r[k]}/></Section></MetricPage>}

export function MonitoringPage(){const kpis=[{value:'906',label:'Under Monitoring',tone:'blue',icon:'chart'},{value:'112',label:'Improving',tone:'green',icon:'check'},{value:'684',label:'Unchanged',tone:'blue',icon:'clock'},{value:'110',label:'Deteriorating',tone:'red',icon:'alert'},{value:'46',label:'Update Due',tone:'amber',icon:'clock'}];const cols=['Project','Current Concern','Execution Health','Schedule Outlook','Cost Outlook','Last Update','Next Check','Assigned Officer','Trend'].map(x=>({key:x.toLowerCase().replaceAll(' ','_'),label:x}));const rows=monitoring.map((r,i)=>Object.fromEntries([['id',i],...cols.map((c,j)=>[c.key,r[j]])]));return <MetricPage title="Monitoring" subtitle="Track projects requiring continued observation across reporting cycles." kpis={kpis} filters={['Trend','Sector','Assigned Officer','Next Check']} rail={<aside className="stack"><Section title="Monitoring Summary"><div className="donut-wrap"><Donut value={76} label="On schedule"/></div></Section><Section title="Upcoming Checks"><div className="side-list">{monitoring.slice(0,3).map(r=><button key={r[0]}><FileText/>{r[0]}<b>{r[6]}</b></button>)}</div></Section></aside>}><Section title="Projects under continued monitoring"><StandardTable columns={cols} rows={rows} renderCell={(r,k)=>['execution_health','schedule_outlook','cost_outlook'].includes(k)?<StatusPill>{r[k]}</StatusPill>:k==='trend'?<span className={`trend ${r[k]}`}>{r[k]==='improving'?<TrendingUp/>:r[k]==='deteriorating'?<TrendingDown/>:'→'} {r[k]}</span>:r[k]}/></Section></MetricPage>}

export function AnalyticsPage(){return <div className="page"><PageHeroHeader title="Analytics" subtitle="Portfolio patterns for operational monitoring and comparison."/><div className="analytics-grid"><Section title="Portfolio Progress Trend"><div className="chart-pad"><LineChart/></div></Section><Section title="Data Quality Coverage"><div className="donut-wrap"><Donut value={82} label="Good coverage"/></div></Section><Section title="Execution Health by Sector"><Bars items={[{label:'Coal',value:78},{label:'Transport',value:62},{label:'Energy',value:54},{label:'Water',value:41},{label:'Urban',value:36}]}/></Section><Section title="State / Region Overview"><IndiaMap compact/></Section><Section title="Schedule Concern Distribution"><div className="distribution"><StatusPill>High concern · 214</StatusPill><StatusPill>Monitor · 906</StatusPill><StatusPill>On track · 1,747</StatusPill></div></Section><Section title="Similar Project Comparison"><div className="comparison"><strong>Bhatadi Expansion OC</strong><p>Physical progress is 9 percentage points below the median of the selected similar-project group.</p><small>Observational comparison · not a causal claim</small></div></Section></div></div>}

export function ReportsPage(){return <MetricPage title="Reports" subtitle="Access portfolio, project and officer-workflow reporting outputs." kpis={[{value:'24',label:'Recent Reports',tone:'blue',icon:'chart'},{value:'12',label:'Monthly Monitoring',tone:'green',icon:'check'},{value:'38',label:'Project Briefs',tone:'amber',icon:'clock'},{value:'16',label:'Review Reports',tone:'purple',icon:'search'}]}><Section title="Report library" action={<button className="btn primary"><FileText/>Prepare report</button>}><div className="report-grid">{reports.map(r=><article key={r[0]}><FileText/><div><h3>{r[0]}</h3><p>{r[1]} · {r[2]}</p><small>Updated {r[3]}</small></div><button className="btn secondary"><Download/>Export</button></article>)}</div></Section><p className="prototype-note">Report export buttons are visual placeholders; PDF generation will be connected during backend integration.</p></MetricPage>}

export function WorkspacePage(){return <MetricPage title="My Workspace" subtitle="Your assigned reviews, pending actions and saved projects." kpis={[{value:'28',label:'Assigned Reviews',tone:'blue',icon:'chart'},{value:'9',label:'Pending Actions',tone:'red',icon:'alert'},{value:'14',label:'Saved Projects',tone:'amber',icon:'search'},{value:'22',label:'Recent Activities',tone:'green',icon:'check'}]}><div className="workspace-grid"><Section title="Assigned reviews"><div className="task-list">{projects.slice(0,4).map(p=><Link key={p.id} to="/officer/reviews/REV-2026-0143"><ClipboardRow project={p.name} meta={`${p.id} · Due 25 Jun`}/></Link>)}</div></Section><Section title="Pending actions"><div className="task-list">{['Verify source evidence','Review revised timeline','Contact implementing agency','Confirm next reporting date'].map((x,i)=><ClipboardRow key={x} project={x} meta={projects[i].name}/>)}</div></Section></div></MetricPage>}
const ClipboardRow=({project,meta})=><div className="task-row"><CheckCircle2/><div><strong>{project}</strong><small>{meta}</small></div></div>;

export function NotificationsPage(){return <MetricPage title="Notifications" subtitle="Project, alert and review updates relevant to your work."><Section title="Notification center" action={<button className="text-link">Mark all as read</button>}><div className="notification-list">{notifications.map(([type,text,date,read])=><article className={read?'read':''} key={text}><span><Bell/></span><div><strong>{type}</strong><p>{text}</p></div><time>{date}</time></article>)}</div></Section></MetricPage>}

export function SettingsPage(){return <MetricPage title="Settings" subtitle="Manage local prototype display and notification preferences."><div className="settings-grid"><Section title="Profile"><div className="settings-form"><label>Display name<input value="sih-demo-officer" readOnly/></label><label>Role<input value="Monitoring Officer" readOnly/></label><label>Reporting unit<input value="Central Monitoring Unit" readOnly/></label></div></Section><Section title="Display preferences"><div className="settings-form"><label>Default landing page<select><option>Officer Overview</option><option>Projects</option></select></label><label>Table density<select><option>Comfortable</option><option>Compact</option></select></label></div></Section><Section title="Notification preferences"><div className="toggle-list">{['New governed alerts','Review assignments','Monitoring reminders','Monthly report updates'].map(x=><label key={x}><span>{x}</span><input type="checkbox" defaultChecked/></label>)}</div></Section></div><p className="prototype-note">Preferences are local frontend controls in this prototype and are not connected to account security settings.</p></MetricPage>}
