import React, { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { AlertTriangle, CheckCircle2, ClipboardCheck, Clock3, FileText, UserRound } from 'lucide-react';
import MilestoneJourney from '../../components/project/MilestoneJourney';
import { FilterBar, KpiStrip, MetricPage, PageHeroHeader, Section, StandardTable, StatusPill } from '../../components/common/PageKit';
import { alerts, alertKpis } from '../../data/mock/alerts';
import { reviews, reviewKpis } from '../../data/mock/reviews';

const alertColumns=[{key:'project',label:'Project'},{key:'type',label:'Alert Type'},{key:'priority',label:'Priority'},{key:'reason',label:'Why this alert was raised'},{key:'status',label:'Status'},{key:'assigned',label:'Assigned To'},{key:'updated',label:'Updated'},{key:'action',label:'Action'}];
const alertCell=(a,k)=>k==='project'?<><span className="project-name">{a.project}</span><span className="project-code">{a.projectId}</span></>:['priority','status'].includes(k)?<StatusPill>{a[k]}</StatusPill>:k==='action'?<Link className="btn secondary" to={`/officer/alerts/${a.id}`}>Open alert</Link>:a[k];

export function AlertsPage(){const [selected,setSelected]=useState(alerts[0]);return <MetricPage title="Alerts" subtitle="Evidence-backed cases requiring officer attention and follow-up." kpis={alertKpis} filters={['Severity','Status','Ministry / Sector','Alert Type','Data Quality','Reporting Month']} rail={<AlertPreview alert={selected}/>}><Section title="Alert list" action={<span className="section-meta">Showing 1–{alerts.length} of 214 active alerts</span>}><div onClick={e=>{const row=e.target.closest('tr[data-id]');if(row)setSelected(alerts.find(a=>a.id===row.dataset.id))}}><div className="table-scroll"><table className="data-table"><thead><tr>{alertColumns.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{alerts.map(a=><tr key={a.id} data-id={a.id} className={selected.id===a.id?'selected-row':''}>{alertColumns.map(c=><td key={c.key}>{alertCell(a,c.key)}</td>)}</tr>)}</tbody></table></div></div></Section></MetricPage>}
function AlertPreview({alert}){return <aside className="surface detail-rail"><header className="section-head"><h2>Alert Details</h2></header><div className="rail-body"><StatusPill>{alert.priority} priority</StatusPill><h3>{alert.project}</h3><span className="project-code">{alert.id} · {alert.type}</span><InfoBlock title="What happened?">{alert.reason}. This signal requires evidence review rather than an automatic conclusion.</InfoBlock><InfoBlock title="Evidence Summary">Latest source report, project identity and milestone record are available.</InfoBlock><InfoBlock title="Recommended Next Step">Review the latest evidence and confirm the project response.</InfoBlock><div className="rail-meta"><span>Current Review State</span><StatusPill>{alert.status}</StatusPill><span>Assigned To</span><b>{alert.assigned}</b></div><Link className="btn primary full" to={`/officer/alerts/${alert.id}`}>Open full alert</Link></div></aside>}
const InfoBlock=({title,children})=><div className="info-block"><strong>{title}</strong><p>{children}</p></div>;

export function AlertDetailsPage(){const {alertId}=useParams();const a=alerts.find(x=>x.id===alertId)||alerts[0];return <div className="page"><PageHeroHeader title="Alert Details" subtitle="View alert information, evidence and take an appropriate action." breadcrumb="Home / Alerts / Alert Details"/><div className="detail-layout"><div className="stack"><Section title={a.project} action={<StatusPill>{a.priority} priority</StatusPill>}><div className="summary-grid"><Summary label="Alert ID" value={a.id}/><Summary label="Alert Type" value={a.type}/><Summary label="Current Status" value={a.status}/><Summary label="Assigned To" value={a.assigned}/><Summary label="Updated" value={a.updated}/><Summary label="Linked Review" value="REV-2026-0143"/></div></Section><Section title="Why this alert was raised"><div className="reason-grid">{[['Milestone delayed','Latest milestone is behind the approved schedule.'],['Expenditure review','Financial and physical delivery require comparison.'],['Evidence needs review','Supporting documents require officer confirmation.'],['Progress below plan','Reported physical progress is below plan.']].map(x=><InfoCard key={x[0]} title={x[0]} text={x[1]}/>)}</div></Section><Section title="Evidence Snapshot"><div className="summary-grid"><Summary label="Reporting Month" value="May 2026"/><Summary label="Source Report ID" value="PRH-400033-MR-2026-05"/><Summary label="Page Reference" value="Pages 14–16"/><Summary label="Execution Health" value="Needs attention"/><Summary label="Data Quality" value="Good"/><Summary label="Officer Attention" value="Pending review"/></div></Section><Section title="Activity / Audit Log"><div className="audit-list">{[['12 Jun 2026, 10:28','System','Alert created'],['12 Jun 2026, 14:15','R. Kumar','Acknowledged'],['13 Jun 2026, 09:30','S. Mehta','Evidence opened']].map(r=><div key={r.join()}>{r.map(c=><span key={c}>{c}</span>)}</div>)}</div></Section></div><aside className="stack"><Section title="Alert Lifecycle"><Lifecycle stages={['Alert created','In review','Under monitoring','Escalated (if required)','Resolved']} current={1}/></Section><Section title="Recommended Actions"><div className="action-grid">{['Acknowledge','Assign Review','Add Note','Request Verification','Move to Monitoring','Resolve Alert','Escalate'].map((x,i)=><button className={`btn ${i===0?'primary':'secondary'}`} key={x}>{x}</button>)}</div></Section><Section title="Project Quick Context"><div className="rail-body"><Summary label="Project" value={a.project}/><Summary label="Sector" value="Coal"/><Summary label="Project Status" value="Under implementation"/><Link className="btn secondary full" to={`/officer/projects/${a.projectId}`}>View project</Link></div></Section></aside></div></div>}

const reviewColumns=[{key:'project',label:'Project'},{key:'type',label:'Linked Alert Type'},{key:'state',label:'Review State'},{key:'priority',label:'Priority'},{key:'assigned',label:'Assigned To'},{key:'next',label:'Next Review Date'},{key:'updated',label:'Last Updated'},{key:'action',label:'Action'}];
export function ReviewsPage(){return <MetricPage title="Reviews" subtitle="Track officer follow-up, assignments, notes and resolution workflow." kpis={reviewKpis} filters={['Review State','Priority','Assigned To','Sector','Reporting Month']} rail={<aside className="stack"><Section title="Review Workload"><div className="donut-placeholder"><b>76</b><span>Total Reviews</span></div><div className="legend-list"><StatusPill>In progress · 18</StatusPill><StatusPill>Monitoring · 24</StatusPill><StatusPill>Action required · 16</StatusPill></div></Section><Section title="My Pending Actions"><div className="side-list">{reviews.slice(0,4).map(r=><Link key={r.id} to={`/officer/reviews/${r.id}`}><FileText/>{r.project}<b>{r.next}</b></Link>)}</div></Section></aside>}><Section title="Review Queue" action={<span className="section-meta">Showing 1–{reviews.length} of 76 reviews</span>}><StandardTable columns={reviewColumns} rows={reviews} renderCell={(r,k)=>k==='project'?<><span className="project-name">{r.project}</span><span className="project-code">{r.projectId}</span></>:['state','priority'].includes(k)?<StatusPill>{r[k]}</StatusPill>:k==='action'?<Link className="btn secondary" to={`/officer/reviews/${r.id}`}>Open review</Link>:r[k]}/></Section></MetricPage>}

export function ReviewDetailsPage(){const {reviewId}=useParams();const r=reviews.find(x=>x.id===reviewId)||reviews[0];return <div className="page"><PageHeroHeader title="Review Details" subtitle="Officer workflow, evidence and follow-up for the selected case." breadcrumb="Reviews / Open Review"/><div className="detail-layout"><div className="stack"><Section title={r.project} action={<StatusPill>{r.state}</StatusPill>}><div className="summary-grid"><Summary label="Review ID" value={r.id}/><Summary label="Review Type" value={r.type}/><Summary label="Priority" value={r.priority}/><Summary label="Assigned Officer" value={r.assigned}/><Summary label="Due Date" value={r.next}/><Summary label="Linked Alert" value="ALRT-2026-0187"/></div></Section><Section title="Review Workflow"><Lifecycle horizontal stages={['Opened','Assigned','Evidence Checked','Action Planned','Monitoring','Closed']} current={2}/></Section><Section title="Officer Notes"><div className="notes-list">{[['Evidence documents reviewed','Reviewed the submitted progress report and source references.'],['Discussion with project team','Clarification requested on milestone movement.'],['Updated timeline needed','Revised milestone plan requested from the implementing agency.']].map(x=><InfoCard key={x[0]} title={x[0]} text={x[1]}/>)}</div></Section><Section title="Recommended Actions"><div className="checklist">{['Verify source submission and documents','Contact implementing agency','Check progress variance with approved schedule','Schedule follow-up review','Update review outcome'].map((x,i)=><label key={x}><input type="checkbox" defaultChecked={i<2}/><span>{x}</span><StatusPill>{i<2?'Completed':i===2?'In progress':'Pending'}</StatusPill></label>)}</div></Section><Section title="Review Outcome and Next Step"><div className="outcome-grid">{['Continue monitoring','Seek clarification','Escalate','Close with no action'].map((x,i)=><button className={i===0?'selected':''} key={x}>{x}</button>)}</div></Section></div><aside className="stack"><Section title="Project Snapshot"><div className="rail-body"><Summary label="Project" value={r.project}/><Summary label="Sector" value="Coal"/><Summary label="Data Quality" value="Good"/><Summary label="Schedule Outlook" value="Moderate early warning"/></div></Section><Section title="Evidence Pack"><div className="rail-body"><Summary label="Source Report" value="Monthly Progress Report"/><Summary label="Reporting Month" value="May 2026"/><Summary label="Page Reference" value="Pages 12–14"/><Summary label="Evidence Hash" value="a3f9d2e7…8c4b"/></div></Section><Section title="Milestone Journey"><div className="mini-journey"><MilestoneJourney/></div></Section></aside></div></div>}

function Summary({label,value}){return <div className="summary-item"><span>{label}</span><strong>{value}</strong></div>}
function InfoCard({title,text}){return <article className="info-card"><span><AlertTriangle/></span><div><strong>{title}</strong><p>{text}</p></div></article>}
function Lifecycle({stages,current,horizontal=false}){return <div className={`lifecycle ${horizontal?'horizontal':''}`}>{stages.map((s,i)=><div className={i<current?'done':i===current?'current':''} key={s}><span>{i<current?<CheckCircle2/>:i===current?<ClipboardCheck/>:<Clock3/>}</span><strong>{s}</strong><small>{i===current?'Current stage':i<current?'Completed':'Pending'}</small></div>)}</div>}
