"""Auditable constants for Implementation Watch policy v1.0."""

PHYSICAL_BEHIND_PLAN_THRESHOLD_PP=-10.0
FINANCIAL_BEHIND_PLAN_THRESHOLD_PP=-10.0
FINANCIAL_PHYSICAL_DIVERGENCE_THRESHOLD_PP=15.0
STAGNATION_TRANSITIONS=2
HIGH_REQUIRED_FUTURE_PACE_PP_PER_MONTH=5.0
LOW_PROGRESS_THRESHOLD_PCT=80.0
NEAR_DEADLINE_MONTHS=6.0
SEVERE_MILESTONE_DELAY_DAYS=90
HIGH_LAND_REMAINING_PCT=20.0
PROLONGED_TENDER_CYCLE_DAYS=120
CRITICAL_CLEARANCE_CATEGORIES=frozenset({"CRZ","ENVIRONMENTAL","FOREST","DEFENCE"})
