import React from 'react';
import { RotateCcw, Search } from 'lucide-react';
import { KpiCard, PageHeroHeader, Section, StatusPill } from './Primitives';

export function KpiStrip({items}){return <div className="kpi-grid">{items.map(i=><KpiCard key={i.label} item={i}/>)}</div>}
export function StandardTable({columns,rows,renderCell}){return <div className="table-scroll"><table className="data-table"><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={row.id||index}>{columns.map(c=><td key={c.key}>{renderCell?renderCell(row,c.key):String(row[c.key]??'—')}</td>)}</tr>)}</tbody></table></div>}
export function DataToolbar({search,setSearch,filters=[],sort,setSort,onReset}){return <div className="filter-bar"><label className="search-input"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by project, code, ministry or keyword"/><span className="sr-only">Search</span>{search&&<button type="button" onClick={()=>setSearch('')} aria-label="Clear search">×</button>}</label><div className="filter-row">{filters.map(f=><label key={f.key}><span>{f.label}</span><select aria-label={f.label} value={f.value} onChange={e=>f.onChange(e.target.value)}>{f.options.map(o=><option key={o} value={o}>{o}</option>)}</select></label>)}{sort&&<label><span>Sort by</span><select aria-label="Sort by" value={sort.value} onChange={e=>setSort(e.target.value)}>{sort.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}<button className="reset-filter" type="button" onClick={onReset}><RotateCcw size={16}/>Reset</button></div></div>}
export function Pagination({page,setPage,total,pageSize,setPageSize}){const pages=Math.max(1,Math.ceil(total/pageSize));return <div className="pagination"><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page} of {pages}</span><button disabled={page===pages} onClick={()=>setPage(page+1)}>Next</button><label>Rows <select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1)}}><option>5</option><option>8</option><option>10</option></select></label></div>}
export function EmptyState({label='No matching results.',onReset}){return <div className="empty-state"><strong>{label}</strong><p>Adjust the search or filters and try again.</p>{onReset&&<button className="btn secondary" onClick={onReset}>Reset filters</button>}</div>}
export function MetricPage({title,subtitle,kpis,children,rail}){return <div className="page"><PageHeroHeader title={title} subtitle={subtitle}/>{kpis&&<KpiStrip items={kpis}/>} {rail?<div className="content-grid"><div className="metric-main">{children}</div>{rail}</div>:children}</div>}
export function ToneValue({children}){return <StatusPill>{children}</StatusPill>}
export {Section,StatusPill,PageHeroHeader};
